#Angewandte Statistik
#Uebungsblatt6
#Aufgabe2
#Damit es schneller geht:
#h
mod0 <-glm(goals~1,data=liga,family="poisson")
mod1 <-glm(goals~I(mvo^2),data=liga,family="poisson")
mod2 <-glm(goals~I(mv^2),data=liga,family="poisson")
mod3 <-glm(goals~I(mv^2)+I(mvo^2),data=liga,family="poisson")
mod4 <-glm(goals~home,data=liga,family="poisson")
mod5 <-glm(goals~home+I(mvo^2),data=liga,family="poisson")
mod6 <-glm(goals~home+I(mv^2),data=liga,family="poisson")
mod7 <-glm(goals~home+I(mv^2)+I(mvo^2),data=liga,family="poisson")
mod8 <-glm(goals~mvo,data=liga,family="poisson")
mod9 <-glm(goals~mvo+I(mvo^2),data=liga,family="poisson")
mod10<-glm(goals~mvo+I(mv^2),data=liga,family="poisson")
mod11<-glm(goals~mvo+I(mv^2)+I(mvo^2),data=liga,family="poisson")
mod12<-glm(goals~mvo+home,data=liga,family="poisson")
mod13<-glm(goals~mvo+home+I(mvo^2),data=liga,family="poisson")
mod14<-glm(goals~mvo+home+I(mv^2),data=liga,family="poisson")
mod15<-glm(goals~mvo+home+I(mv^2)+I(mvo^2),data=liga,family="poisson")
mod16<-glm(goals~mv,data=liga,family="poisson")
mod17<-glm(goals~mv+I(mvo^2),data=liga,family="poisson")
mod18<-glm(goals~mv+I(mv^2),data=liga,family="poisson")
mod19<-glm(goals~mv+I(mv^2)+I(mvo^2),data=liga,family="poisson")
mod20<-glm(goals~mv+home,data=liga,family="poisson")
mod21<-glm(goals~mv+home+I(mvo^2),data=liga,family="poisson")
mod22<-glm(goals~mv+home+I(mv^2),data=liga,family="poisson")
mod23<-glm(goals~mv+home+I(mv^2)+I(mvo^2),data=liga,family="poisson")
mod24<-glm(goals~mv+mvo,data=liga,family="poisson")
mod25<-glm(goals~mv+mvo+I(mvo^2),data=liga,family="poisson")
mod26<-glm(goals~mv+mvo+I(mv^2),data=liga,family="poisson")
mod27<-glm(goals~mv+mvo+I(mv^2)+I(mvo^2),data=liga,family="poisson")
mod28<-glm(goals~mv+mvo+home,data=liga,family="poisson")
mod29<-glm(goals~mv+mvo+home+I(mvo^2),data=liga,family="poisson")
mod30<-glm(goals~mv+mvo+home+I(mv^2),data=liga,family="poisson")
mod31<-glm(goals~mv+mvo+home+I(mv^2)+I(mvo^2),data=liga,family="poisson")